In [1]:
include("iLQR.jl")
include("dynamics.jl")

iLQR.Model(iLQR.fc, 4, 1)

In [2]:
using iLQR

In [5]:
## Double pendulum
urdf_dp = "urdf/doublependulum.urdf"
dp = iLQR.Model(urdf_dp)

# initial and goal states
x0 = [0.;0.;0.;0.]
xf = [pi;0.;0.;0.]

# costs
Q = 0.0001*eye(4)
Qf = 250.0*eye(4)
R = 0.0001*eye(2)

# simulation
tf = 5.0
dt = 0.1

obj = iLQR.Objective(Q,R,Qf,tf,x0,xf)
solver = iLQR.Solver(dp,obj,dt=dt);

In [7]:
U = 10.0*rand(solver.model.m,solver.N)
X_dp, U_dp = @time iLQR.solve(solver,U);

LoadError: UndefVarError: solve_sqrt not defined

In [12]:
X_dp[:,end]

4-element Array{Float64,1}:
  3.14096    
 -0.000255546
  0.000563909
 -0.000193513

In [77]:
## BoB
n = 4
m = 1

# initial and goal states
x0 = [.1;0.;0.;0.]
xf = [.5;0.;0.;0.]

#set_configuration!(state, x0[1:2])
#set_velocity!(state, x0[3:4])

# costs
Q = 5e-4*eye(n)
Qf = 500.0*eye(n)
R = 1e-5*eye(m)

# simulation
tf = 1.0
dt = 0.01

obj = iLQR.Objective(Q,R,Qf,tf,x0,xf)
solver = iLQR.Solver(ballonbeam,obj)
u = ones(m,solver.N)*11

1×10 Array{Float64,2}:
 11.0  11.0  11.0  11.0  11.0  11.0  11.0  11.0  11.0  11.0

In [81]:
x,u = iLQR.solve(solver,u)

Cost: 0.5842129116391265
Cost: 0.562731870863896
Cost: 0.5328879202116943
Cost: 0.4664224959632715
Cost: 0.055458890470258954
Cost: 0.05255860252594142
Cost: 0.047985845692635115
Cost: 0.033204603658799105
Cost: 0.03307311801826171
Cost: 0.032901751430380946


([0.1 0.1 … 0.496028 0.500049; 0.0 -0.23631 … 0.16448 0.00143103; 0.0 0.0558422 … -0.12157 0.000574857; 0.0 -4.72619 … -3.12429 5.23828e-5], [-5.58811 33.8462 … 28.7945 6.9004e-310])

In [79]:
x[:,end]

4-element Array{Float64,1}:
 0.501483   
 0.00401038 
 0.00408662 
 0.000849233

In [80]:
u += randn(size(u))*1

1×10 Array{Float64,2}:
 -5.37549  33.1822  23.5858  7.22139  …  -3.34205  29.119  0.0492478